directories:
  output: release
  buildResources: build
appId: com.cute-go.app
productName: CuteGo
npmRebuild: false
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
win:
  target: nsis
  icon: resources/icon.ico
extraResources:
  - from: resources/katago
    to: katago
electronVersion: 40.0.0
